### cadastrar usuario
POST http://localhost:3000/usuario
Content-Type: application/json

{
    "nome": "henrique",
    "email": "henrique@email.com",
    "senha": "senha123"
}

### consultar usuario
GET http://localhost:3000/usuario/1